updated teiler

diff --git a/teiler b/teiler
--- a/teiler
+++ b/teiler
@@ -1,14 +1,13 @@
 #!/bin/bash
 
-# start
-# Interface is created, choices are defined in variable "menu"
-# if function isRecording is positive, menu is altereed
+# Menus
+
 mainMenu () {
     isRecording && STATE_RECORDING="3. Stop recording screencast"
     menu=("0: Cancel"
           "1. Screenshot (Fullscreen)"
           "2. Screenshot (Area)"
-          "${STATE_RECORDING:-"3. Record screencast"}"
+          "${STATE_RECORDING:-"3. Screencast"}"
           "---"
           "4. Copy Last Image to Clipboard"
           "5. Upload Clipboard Content"
@@ -16,7 +15,6 @@ mainMenu () {
           "---"
           "$quickName")
 
-# read variable menu and pipe it to dmenu_t
     prompt() {
         printf "%s\n" "$@" | dmenu_t -p "Teiler:"
     }
@@ -25,19 +23,32 @@ mainMenu () {
         printf "%s\n" "$@" | dmenu_t -p "Delay:"
     }
 
-# for each entry in variable "menu" define an action
-# if function isRecording is positive actions are altered
     case "$(prompt "${menu[@]}")" in 
         0:*) exit ;;
         1.*) delayPrompt screenshot -d ;;
         2.*) delayPrompt screenshot -s -d ;;
-        3.*) isRecording && stopRecording || screencast ;;
+        3.*) isRecording && stopRecording && sleep 2 && askPrompt || screencast ;;
         4.*) imgClip ;;
         5.*) clipUpload ;;
         6.*) uploadMenu ;;
         7.*) quick ;;
           *) exit
     esac
+}
+
+askPrompt () {
+    menu=("1. Yes"
+          "2. No")
+    
+    prompt() { 
+        printf "%s\n" "$@" | dmenu_t -p "Upload Video?"
+    }
+       
+       case "$(prompt "${menu[@]}")" in
+       1.*) instantUpload mp4 "$scp_path_vid" "$http_vid" ;;
+       2.*) exit ;;
+         *) exit
+   esac
 }
 
 uploadMenu () {
@@ -61,38 +72,55 @@ uploadMenu () {
    esac
 }
 
+delayPrompt () {
+    t=$(promptDelay 0 2 5 10 20 30 '<< back to Main Menu')
+    [[ "$t" = *[[:digit:]]* ]] || mainMenu
+    [[ "$t" -gt 2 ]] && {
+        notify "$time" "Screenshot will be taken in $t seconds"
+        countdown "$t" | progress 0 "$t" &
+        DELAY_PID=$!
+    }
+    "$@" $((t+1))
+    unset DELAY_PID
+    killCountdown
+}
 
-# quickoption (configurable in config file)
+
+# main function
+
+# actual screenshot function
+screenshot () {
+    type scrot &>/dev/null || { echo "Missing scrot!"; exit 1; }
+    [[ -f "${img_path}/lastimg.png" ]] && rm "${img_path}/lastimg.png"
+    scrot "$@" "${img_path}/lastimg.png"
+    notify "$time" "Screenshot saved"
+    archiveImage
+}
+
 quick () {
     screenshot -d $quickDelay $quickArea
     instantUpload png "$scp_path_img" "$http_img"
 }
 
 
-
-# record the screen with ffmpeg. 
-# function isRecording is called to make sure that no recording is active.
+# screencast related functions (screencast, isRecording, stopRecording)
 screencast () {
-    type avconv xdotool xwininfo || type ffmpeg xdotool xwininfo &>/dev/null || { echo "Missing Dependencies"; exit 1; }
+    type avconv || type ffmpeg &>/dev/null || { echo "Missing Dependencies"; exit 1; }
     isRecording && {
         notify "$time" 'Screencast already in progress'
         echo "Already recording Screen"; exit 1;
 }
     [[ -f "${vid_path}/lastvid.mp4" ]] && rm "${vid_path}/lastvid.mp4"
-    $encoder -f x11grab -s $res -i $ffmpeg_display+$ffmpeg_x_offset $ffaudio $encopts "${vid_path}/lastvid.mp4" &
+    $encoder -f x11grab -s $res -i $ffmpeg_display+$ffmpeg_offset $ffaudio $encopts "${vid_path}/lastvid.mp4" &
     echo "$!" > "$SCREENCAST_PIDFILE"
     indicator
     notify "$time" "Screencast started"
 }
 
-# Draws a little Recording Indicator on screen. 
-indicator () {
-    echo "$rec_text" | dzen2 -fn "$rec_font" -fg "$rec_nf" -bg "$rec_sf" -w 120 -x $(( ( $(xininfo -mon-width)-120)/2 )) -xs $(echo $(( $(xininfo -active-mon) + 1 ))) -p &
-    echo "$!" > "$INDICATOR_PIDFILE"
+isRecording () {
+    [[ -f "$SCREENCAST_PIDFILE" ]] || return 1;
 }
 
-# Checks the pidfile that is written by the screencast function
-# if present ffmpeg is killed properly and a notification is send
 stopRecording () {
     local pid
     [[ -f $SCREENCAST_PIDFILE ]] && {
@@ -107,22 +135,47 @@ stopRecording () {
     return 0
 }
 
-# Draws a menu with with entries defined in variable "t"
-# delayCountdown variable is then called
-delayPrompt () {
-    t=$(promptDelay 0 2 5 10 20 30 '<< back to Main Menu')
-    [[ "$t" = *[[:digit:]]* ]] || mainMenu
-    [[ "$t" -gt 2 ]] && {
-        notify "$time" "Screenshot will be taken in $t seconds"
-        countdown "$t" | progress 0 "$t" &
-        DELAY_PID=$!
-    }
-    "$@" $((t+1))
-    unset DELAY_PID
-    killCountdown
+
+# copy last image to clipboard
+imgClip () {
+    imgclip "$img_path"/lastimg.png &
 }
 
-# shows a countdown based on variable "t" which is set in the delayPrompt menu
+
+# archiving functions
+archiveImage () {
+    [[ "$archive_img" = '1' ]] || return
+    mv "${img_path}/lastimg.png" "${img_path}/${img_filemask}.png"
+    ln -s "${img_path}/${img_filemask}.png" "${img_path}/lastimg.png"
+}
+
+
+archiveVid () {
+    [[ "$archive_vid" = '1' ]] || return
+    mv "${vid_path}/lastvid.mp4" "${vid_path}/${vid_filemask}.mp4"
+    ln -s "${vid_path}/${vid_filemask}.mp4" "${vid_path}/lastvid.mp4"
+}
+
+
+archivePaste () {
+    [[ "$archive_paste" = '1' ]] || return
+    mv "${paste_path}/lastpaste.paste" "${paste_path}/${paste_filemask}.paste"
+    ln -s "${paste_path}/${paste_filemask}.paste" "${paste_path}/lastpaste.paste"
+}
+
+
+# misc functions
+
+# notification and indicator functions
+notify () {
+    notify-send -u low --hint=int:transient:1 -t "$1" "Teiler" "$2"
+}
+
+indicator () {
+    echo "$rec_text" | dzen2 -fn "$rec_font" -fg "$rec_nf" -bg "$rec_sf" -w 120 \
+    -x $(( ( $(xininfo -mon-width)-120)/2 )) -xs $(echo $(( $(xininfo -active-mon) + 1 ))) -p &
+    echo "$!" > "$INDICATOR_PIDFILE"
+}
 
 function countdown {
     for i in $(seq $[$1-1] -1 0); do
@@ -140,92 +193,12 @@ function killCountdown {
 }
 
 function progress {
-    gdbar -min $1 -max $2 -w 100 -h 8 | dzen2 -fn "$rec_font" -fg "$rec_nf" -bg "$rec_sf" -w 120 -x $(( ( $(xininfo -mon-width)-120)/2 )) -xs $(echo $(( $(xininfo -active-mon) + 1 ))) -p 1
+    gdbar -min $1 -max $2 -w 100 -h 8 | dzen2 -fn "$rec_font" -fg "$rec_nf" -bg "$rec_sf" -w 120 \
+    -x $(( ( $(xininfo -mon-width)-120)/2 )) -xs $(echo $(( $(xininfo -active-mon) + 1 ))) -p 1
 }
 
 
-# defines a countdown for the amount of time the image is kept in clipboard
-delayClip () {
-    for ((n=${1:-10}; n>=0; --n)); do  
-        printf "\n%s " $n
-        sleep 1
-    done
-    printf "\r \r"  # clean up
-}
-
-# calls external python script to hold an actual image in clipboard
-# function delayClip is called to draw a countdown on screen
-# After the countdown is done, clipboard is cleared, by killing the python script
-imgClip () {
-    imgclip "$img_path"/lastimg.png &
-}
-
-# checks if pid file written by the screencast function exists.
-isRecording () {
-    [[ -f "$SCREENCAST_PIDFILE" ]] || return 1;
-}
-
-# checks dependency for screenshots and captures the screen
-screenshot () {
-    type scrot &>/dev/null || { echo "Missing scrot!"; exit 1; }
-    [[ -f "${img_path}/lastimg.png" ]] && rm "${img_path}/lastimg.png"
-    scrot "$@" "${img_path}/lastimg.png"
-    notify "$time" "Screenshot saved"
-    archiveImage
-}
-
-# Used for sending Notifications
-notify () {
-    notify-send -u low --hint=int:transient:1 -t "$1" "Teiler" "$2"
-}
-
-
-clipUpload () {
-    [[ -f "${paste_path}/lastpaste.paste" ]] && rm "${paste_path}/lastpaste.paste"
-    x_clip
-    (xclip -o) > "${paste_path}/lastpaste.paste"
-    notify "$time" "Paste saved"
-    if [[ $paste_ul == scp ]]
-        then scp "${paste_path}/lastpaste.paste" "$scp_host":"$scp_path_paste"/"$paste_filemask".paste
-        notify-send -u low --hint=int:transient:1 -t "$time" "Paste Uploaded" ""$http_paste"/$paste_filemask.paste"
-        echo -n ""$http_paste"/$paste_filemask.paste" | xclip
-    elif [[ $paste_ul == fb ]]
-        then fb "${paste_path}/lastpaste.paste"
-        notify-send -u low --hint=int:transient:1 -t "$time" "Paste Uploaded" "$(echo -n $(xclip -o))"
-    elif [[ $paste_ul == ix ]]
-        then ix "${paste_path}/lastpaste.paste" | xclip
-        notify-send -u low --hint=int:transient:1 -t "$time" "Paste Uploaded" "$(echo -n $(xclip -o))"
-    fi
-    x_clip
-    archivePaste
-}
-
-
-# if set in config, this will rename lastimg.png to the filemask defined in config.
-# then a symlink back to lastimg.png is created
-archiveImage () {
-    [[ "$archive_img" = '1' ]] || return
-    mv "${img_path}/lastimg.png" "${img_path}/${img_filemask}.png"
-    ln -s "${img_path}/${img_filemask}.png" "${img_path}/lastimg.png"
-}
-
-
-# same as archiveImage but for video files created by screencast function
-archiveVid () {
-    [[ "$archive_vid" = '1' ]] || return
-    mv "${vid_path}/lastvid.mp4" "${vid_path}/${vid_filemask}.mp4"
-    ln -s "${vid_path}/${vid_filemask}.mp4" "${vid_path}/lastvid.mp4"
-}
-
-
-archivePaste () {
-    [[ "$archive_paste" = '1' ]] || return
-    mv "${paste_path}/lastpaste.paste" "${paste_path}/${paste_filemask}.paste"
-    ln -s "${paste_path}/${paste_filemask}.paste" "${paste_path}/lastpaste.paste"
-}
-
-
-# shows a list of files using dmenu. this is called by the uploadMenu function
+# filelistings for the upLoad function
 imgListFiles () {
     ls -t -1 "$img_path"/"$namekey"-*."$1" | dmenu_t -p "Select File:"
 }
@@ -235,64 +208,100 @@ vidListFiles () {
 }
 
 
-# this function checks for filetype and makes sure
-# that images and videos are uploaded to the appropriate directories from config file
-# if uploader is set to fb, it will simply upload the given file
-upLoad () {
-    if [[ $1 == png ]]
-        then type="Image"
-    elif [[ $1 == mp4 ]]
-        then type="Video"
-    fi
-    if [[ "$ul" == "scp" ]]
-        then scp "$1" "$scp_host":/"$2/"
-        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$3/$(basename "$1")"
-        echo -n "$3/$(basename "$1")" | xclip
-    elif [[ "$ul" == "fb" ]]
-        then fb "$1" | xclip
-        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$(xclip -o)"
-    elif [[ "$ul" == "imgur" ]]
-        then imgur "$1"
-        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$(xclip -o)"
+# horrible long upload functions
+clipUpload () {
+    [[ -f "${paste_path}/lastpaste.paste" ]] && rm "${paste_path}/lastpaste.paste"
+    x_clip
+    (xclip -o) > "${paste_path}/lastpaste.paste"
+    notify "$time" "Paste saved"
+
+    if [[ $paste_ul == scp ]]; then
+        scp "${paste_path}/lastpaste.paste" "$scp_host":"$scp_path_paste"/"$paste_filemask".paste
+        notify-send -u low --hint=int:transient:1 -t "$time" "Paste Uploaded" "${http_paste}/${paste_filemask}.paste"
+        echo -n "${http_paste}/${paste_filemask}.paste" | xclip
+    elif [[ $paste_ul == fb ]]; then
+        fb "${paste_path}/lastpaste.paste"
+        notify-send -u low --hint=int:transient:1 -t "$time" "Paste Uploaded" "$(echo -n $(xclip -o))"
+    elif [[ $paste_ul == ix ]]; then
+        x_xclip
+        xclip -o 2>&1 | curl -F 'f:1=<-' ix.io | tr -d "\n" | xclip
+        notify-send -u low --hint=int:transient:1 -t "$time" "Paste Uploaded" "$(echo -n $(xclip -o))"
     fi
     x_clip
+    archivePaste
 }
 
-
-# this will upload lastimg.png or lastvid.mp4, depending on the option chosen in uploadMenu
-instantUpload () {
-    if [[ $1 == png ]]
-        then file=$(readlink "$img_path/lastimg.png")
+upLoad () {
+    if [[ $1 == png ]]; then
         type="Image"
-    elif [[ $1 == mp4 ]]
-        then file=$(readlink "$vid_path/lastvid.mp4")
+    elif [[ $1 == mp4 ]]; then
         type="Video"
     fi
-    if [[ "$ul" == scp ]]
-        then scp "$file" "$scp_host":/"$2/"
-        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$3/$(basename "$file")"
-        echo -n "$3/$(basename "$file")" | xclip
-    elif [[ "$ul" == fb ]]
-        then fb "$file" | xclip
+    if [[ "$ul" == "scp" ]]; then
+        scp "$1" "$scp_host":/"$2/"
+        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$3/$(basename "$1")"
+        echo -n "$3/$(basename "$1")" | xclip
+    elif [[ "$ul" == "fb" ]]; then
+        fb "$1"
         notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$(xclip -o)"
-    elif [[ "$ul" == imgur ]]
-        then imgur "$file"
-        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$(xclip -o)"
+    elif [[ "$ul" == "imgur" ]]; then
+        if [[ $1 == mp4 ]]; then
+            notify-send -u critical --hint=int:transient:1 -t "$time" "teiler" "imgur does not support Videos"
+        else 
+            imgur "$1"
+            notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$(xclip -o)"
+        fi
     fi
     x_clip
 }
 
-# Make sure Clipboards are synced
+instantUpload () {
+    if [[ $1 == png ]]; then
+        if [[ "$archive_img" == 1 ]]; then
+            file=$(readlink "$img_path"/lastimg.png)
+        else 
+            file="$img_path/lastimg.png"
+        fi
+        type="Image"
+    elif [[ $1 == mp4 ]]; then
+        if [[ "$archive_vid" == 1 ]]; then
+            file=$(readlink "$vid_path"/lastvid.mp4)
+        else 
+            file="${vid_path}/lastvid.mp4"
+        fi
+        type="Video"
+    fi
+    if [[ "$ul" == scp ]]; then
+        echo $file
+        scp "$file" "$scp_host":/"$2/"
+        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$3/$(basename "$file")"
+        echo -n "$3/$(basename "$file")" | xclip
+    elif [[ "$ul" == fb ]]; then
+        fb "$file"
+        notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$(xclip -o)"
+    elif [[ "$ul" == imgur ]]; then
+        if [[ $1 == mp4 ]]; then
+            notify-send -u critical --hint=int:transient:1 -t "$time" "teiler" "imgur does not support Videos"
+        else
+            imgur "$file"
+            notify-send -u low --hint=int:transient:1 -t "$time" "$(echo $type) Uploaded" "$(xclip -o)"
+        fi
+    fi
+    x_clip
+}
+
 x_clip () {
     (xclip -o) | xclip -selection clipboard
 }
 
-# Check if dmenu or simpleswitcher are available 
+################################################################################################################
+
+
 type dmenu &>/dev/null || type simpleswitcher &>/dev/null || { echo "Missing Dependencies"; exit 1; }
 
 
-# set default backend options
 source "$HOME/.config/teiler/config"
+source "$HOME/.config/dmenurc"
 
 if [[ "$backend" == "simpleswitcher" ]]
     then function dmenu_t () {
@@ -305,6 +314,5 @@ elif [[ "$backend" == "dmenu" ]]
 }
 fi
 
-# actually run the script
 mainMenu
 
